services:

  laravel-queues:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queues
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - laravel-queues-mysql
    networks:
      - laravel
    command: php artisan serve --host=0.0.0.0 --port=8000

  laravel-queues-mysql:
    image: mysql:8.0
    container_name: laravel-queues-mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge